/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/rooms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/room-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rate-calendar/{roomTypeCode}/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["putManual"];
        post?: never;
        delete: operations["deleteManual"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/guests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put: operations["update_2"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/{code}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Silent refresh
         * @description Reads the httpOnly refresh cookie (default name pms_refresh), rotates tokens, and returns a new access JWT. No request body.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Staff logout
         * @description Clears the refresh cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Staff login
         * @description Returns an access JWT in the body and sets the refresh JWT as an httpOnly; SameSite=Strict cookie (ADR-0014).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rooms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/room-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/{id}/no-show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["noShow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/{id}/check-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/{id}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pricing/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refresh_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/guests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reservations/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reservations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rate-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/rate-calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pricing/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pricing/demand-indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["demandIndicators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/timeseries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["timeseries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["kpis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateRoomRequest: {
            roomNumber?: string;
            /** Format: int64 */
            roomTypeId: number;
            /** Format: int32 */
            floor?: number;
            /** @enum {string} */
            status: "AVAILABLE" | "OUT_OF_SERVICE";
            notes?: string;
        };
        RoomResponse: {
            /** Format: int64 */
            id?: number;
            roomNumber?: string;
            /** Format: int64 */
            roomTypeId?: number;
            roomTypeCode?: string;
            /** Format: int32 */
            floor?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "OUT_OF_SERVICE";
            notes?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        UpdateRoomTypeRequest: {
            code?: string;
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity: number;
            basePrice: number;
            minPrice: number;
            maxPrice: number;
            amenities?: string[];
            active: boolean;
            validPriceBand?: boolean;
        };
        RoomTypeResponse: {
            /** Format: int64 */
            id?: number;
            code?: string;
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity?: number;
            basePrice?: number;
            minPrice?: number;
            maxPrice?: number;
            currency?: string;
            amenities?: string[];
            active?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ManualRateOverrideRequest: {
            price: number;
        };
        RateCalendarDayResponse: {
            /** Format: date */
            date?: string;
            price?: number;
            /** @enum {string} */
            source?: "ML_MODEL" | "MANUAL" | "BASE" | "BASE_FALLBACK";
            /** Format: int32 */
            demandIndicator?: number;
            fromCalendar?: boolean;
        };
        UpdateGuestRequest: {
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
        };
        GuestResponse: {
            /** Format: int64 */
            id?: number;
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateReservationRequest: {
            roomTypeCode?: string;
            ratePlanCode?: string;
            /** Format: date */
            checkIn: string;
            /** Format: date */
            checkOut: string;
            /** Format: int32 */
            adults: number;
            guest: components["schemas"]["GuestUpsertRequest"];
            validStay?: boolean;
        };
        GuestUpsertRequest: {
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
        };
        PriceBreakdownLine: {
            /** Format: date */
            date?: string;
            price?: number;
            barPrice?: number;
            /** @enum {string} */
            priceSource?: "ML_MODEL" | "MANUAL" | "BASE" | "BASE_FALLBACK";
        };
        RatePlanSummary: {
            code?: string;
            refundable?: boolean;
            breakfastIncluded?: boolean;
        };
        ReservationResponse: {
            /** Format: int64 */
            id?: number;
            confirmationCode?: string;
            /** @enum {string} */
            status?: "CONFIRMED" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELLED" | "NO_SHOW";
            roomType?: string;
            roomNumber?: string;
            ratePlan?: components["schemas"]["RatePlanSummary"];
            /** Format: date */
            checkIn?: string;
            /** Format: date */
            checkOut?: string;
            /** Format: int32 */
            adults?: number;
            totalPrice?: number;
            currency?: string;
            priceBreakdown?: components["schemas"]["PriceBreakdownLine"][];
            /** @enum {string} */
            source?: "WEB" | "ADMIN";
        };
        TokenResponse: {
            accessToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresIn?: number;
            email?: string;
            fullName?: string;
            /** @enum {string} */
            role?: "ADMIN" | "RECEPTIONIST";
        };
        LoginRequest: {
            email?: string;
            password?: string;
        };
        CreateRoomRequest: {
            roomNumber?: string;
            /** Format: int64 */
            roomTypeId: number;
            /** Format: int32 */
            floor?: number;
            /** @enum {string} */
            status?: "AVAILABLE" | "OUT_OF_SERVICE";
            notes?: string;
        };
        CreateRoomTypeRequest: {
            code?: string;
            name?: string;
            description?: string;
            /** Format: int32 */
            capacity: number;
            basePrice: number;
            minPrice: number;
            maxPrice: number;
            amenities?: string[];
            active?: boolean;
            validPriceBand?: boolean;
        };
        PricingRefreshResponse: {
            status?: string;
            message?: string;
            /** Format: int32 */
            daysUpdated?: number;
        };
        CreateGuestRequest: {
            firstName?: string;
            lastName?: string;
            email?: string;
            phone?: string;
        };
        AvailabilityResponse: {
            /** Format: date */
            checkIn?: string;
            /** Format: date */
            checkOut?: string;
            /** Format: int32 */
            guests?: number;
            currency?: string;
            roomTypes?: components["schemas"]["AvailableRoomTypeAvailability"][];
        };
        AvailableRoomTypeAvailability: {
            code?: string;
            name?: string;
            /** Format: int32 */
            capacity?: number;
            /** Format: int64 */
            roomsLeft?: number;
            nights?: components["schemas"]["NightAvailability"][];
            ratePlans?: components["schemas"]["RatePlanQuote"][];
        };
        NightAvailability: {
            /** Format: date */
            date?: string;
            bar?: number;
            /** @enum {string} */
            priceSource?: "ML_MODEL" | "MANUAL" | "BASE" | "BASE_FALLBACK";
        };
        RatePlanQuote: {
            code?: string;
            name?: string;
            refundable?: boolean;
            breakfastIncluded?: boolean;
            totalPrice?: number;
        };
        PageMeta: {
            /** Format: int32 */
            number?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageResponseRoomResponse: {
            content?: components["schemas"]["RoomResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        PageResponseRoomTypeResponse: {
            content?: components["schemas"]["RoomTypeResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        AdminReservationSummary: {
            /** Format: int64 */
            id?: number;
            confirmationCode?: string;
            /** @enum {string} */
            status?: "CONFIRMED" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELLED" | "NO_SHOW";
            roomType?: string;
            roomNumber?: string;
            guestName?: string;
            guestEmail?: string;
            /** Format: date */
            checkIn?: string;
            /** Format: date */
            checkOut?: string;
            /** Format: int32 */
            adults?: number;
            totalPrice?: number;
            currency?: string;
            /** @enum {string} */
            source?: "WEB" | "ADMIN";
        };
        PageResponseAdminReservationSummary: {
            content?: components["schemas"]["AdminReservationSummary"][];
            page?: components["schemas"]["PageMeta"];
        };
        RatePlanResponse: {
            /** Format: int64 */
            id?: number;
            code?: string;
            name?: string;
            description?: string;
            refundable?: boolean;
            breakfastIncluded?: boolean;
            priceModifier?: number;
            active?: boolean;
            /** Format: int32 */
            sortOrder?: number;
        };
        RateCalendarResponse: {
            roomTypeCode?: string;
            days?: components["schemas"]["RateCalendarDayResponse"][];
        };
        PricingEventResponse: {
            id?: string;
            title?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            impactScore?: number;
            confidence?: number;
            rationale?: string;
            source?: string;
        };
        DemandIndicatorPoint: {
            /** Format: date */
            date?: string;
            /** Format: int32 */
            demandIndicator?: number;
        };
        PageResponseGuestResponse: {
            content?: components["schemas"]["GuestResponse"][];
            page?: components["schemas"]["PageMeta"];
        };
        DashboardDayPoint: {
            /** Format: date */
            date?: string;
            occupancy?: number;
            adr?: number;
            /** Format: int64 */
            roomsOccupied?: number;
            /** Format: int64 */
            roomsSellable?: number;
        };
        DashboardTimeseriesResponse: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            currency?: string;
            points?: components["schemas"]["DashboardDayPoint"][];
        };
        DashboardKpisResponse: {
            /** Format: date */
            businessDate?: string;
            occupancyToday?: number;
            /** Format: int64 */
            roomsOccupiedToday?: number;
            /** Format: int64 */
            roomsSellable?: number;
            /** Format: int64 */
            arrivalsToday?: number;
            /** Format: int64 */
            departuresToday?: number;
            mtdRevenue?: number;
            currency?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomTypeResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoomTypeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomTypeResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putManual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomTypeCode: string;
                date: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualRateOverrideRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RateCalendarDayResponse"];
                };
            };
        };
    };
    deleteManual: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roomTypeCode: string;
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGuestRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                roomTypeId?: number;
                status?: "AVAILABLE" | "OUT_OF_SERVICE";
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseRoomResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                active?: boolean;
                query?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseRoomTypeResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoomTypeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RoomTypeResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: {
                status?: "CONFIRMED" | "CHECKED_IN" | "CHECKED_OUT" | "CANCELLED" | "NO_SHOW";
                from?: string;
                to?: string;
                query?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAdminReservationSummary"];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateReservationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    noShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    checkOut: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    checkIn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    cancel_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    refresh_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PricingRefreshResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                query?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseGuestResponse"];
                };
            };
        };
    };
    create_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGuestRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GuestResponse"];
                };
            };
        };
    };
    lookup: {
        parameters: {
            query: {
                code: string;
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                checkIn: string;
                checkOut: string;
                guests: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AvailabilityResponse"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ReservationResponse"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RatePlanResponse"][];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query: {
                roomTypeCode: string;
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RateCalendarResponse"];
                };
            };
        };
    };
    events: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PricingEventResponse"][];
                };
            };
        };
    };
    demandIndicators: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DemandIndicatorPoint"][];
                };
            };
        };
    };
    timeseries: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardTimeseriesResponse"];
                };
            };
        };
    };
    kpis: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardKpisResponse"];
                };
            };
        };
    };
}
